### ISSUE TITLE
Please clarify on the Response of a CNR

### ISSUE THREAD

**Issue by j-be** [erasmus-without-paper/ewp-specs-api-omobility-la-cnr#1]
I read:
* Servers MUST respond with a valid XML document
* Currently CNR responses are always empty
* Empty string is NOT valid XML (src: https://stackoverflow.com/questions/376306/is-empty-string-valid-xml)

What exactly is a CNR supposed to return?

**Comment by mkurzydlowski** [comment]
The author of the documentation surely meant an empty _omobility-la-cnr-response_ element. Its type is currently _ewp:Empty_:

https://github.com/erasmus-without-paper/ewp-specs-api-omobility-la-cnr/blob/master/response.xsd

**Comment by j-be** [comment]
See, that's what I thought initially, too, but I can't seem to find a XML which successfully validates against the `response.xsd` in Java's JAX-B:
```
<?xml version="1.0" encoding="UTF-8"?>
<omobility-la-cnr-response></omobility-la-cnr-response>
```
doesn't (`cvc-elt.1.a: Cannot find the declaration of element 'omobility-la-cnr-response'.`), neither does
```
<?xml version="1.0" encoding="UTF-8"?>
<omobility-la-cnr-response/>
```
(same error as above).

```
<?xml version="1.0" encoding="UTF-8"?>
```
fails with `Premature end of file.`, same goes for empty string.

Not sure what I am doing wrong. Can you provide an input, that validates? https://www.freeformatter.com/xml-validator-xsd.html seems to run on JAX-B - at least the behavior is the same as with local Java JAX-B.

**Comment by mkurzydlowski** [comment]
I think you forgot to add the namespace:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<omobility-la-cnr-response xmlns="https://github.com/erasmus-without-paper/ewp-specs-api-omobility-la-cnr/tree/stable-v1"></omobility-la-cnr-response>
```

**Comment by j-be** [comment]
Yes, that was the issue. Thank you very much for your help.
